

server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
    sql:
      init:
        mode: always
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: qa
  h2:
    console:
      enabled: true
  jpa:
      show-sql: true


build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
